### PR TITLE
Save on exit

### PR DESCRIPTION
**Pull request by ralesi**
Only save directory listing on exit.  

I have profiled the script and a large portion of the time when performing a `cdX` is saving the cdHistory.  This will save the file on exit with a hook.

### CODE REVIEW

**Comment by vincpa** [comment]
Hi there!

Thanks for the commit and pull request. The problem with hooking into the exit event is that it's only fired if the user clicks the "X" button. Exiting from the command prompt using the "exit" command will exit without the event firing. This means your history changes could be excluded altogether.

How big exactly is your history file which is slowing it down that much?

**Comment by vincpa** [comment]
Just thinking about this, perhaps it should be configurable.

**Comment by ralesi** [comment]
@vincpa,  I just found there is a handler for using exit as well,  would you be interested in this option if both handlers were used?

**Comment by vincpa** [comment]
Absolutely. Losing my history at the start of each session is painful.

**Pull request closed without merging**
